default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: password
  host: localhost
  port: 5432

development:
  <<: *default
  database: print_queue_development

test:
  <<: *default
  database: print_queue_test

production:
  primary: &primary_production
    adapter: postgresql
    encoding: unicode
    url: <%= ENV["DATABASE_URL"] %>
    host: <%= ENV["DATABASE_HOST"] %>
    database: <%= ENV["DATABASE_NAME"] %>
    username: <%= ENV["DATABASE_USER"] %>
    password: <%= ENV["DATABASE_PASSWORD"] %>
    pool: 5
  cable:
    <<: *primary_production
    database: app_production_cable
    migrations_paths: db/cable_migrate
  queue:
    <<: *primary_production
    database: app_production_queue
    migrations_paths: db/queue_migrate
  cache:
    <<: *primary_production
    database: app_production_cache
    migrations_paths: db/cache_migrate